apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typescript-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "typescript-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "typescript-app.name" . }}
  spec:
    containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
        envFrom:
          - configMapRef:
            name: {{ include "typescript-app.fullname" . }}
          - secretRef:
            name: {{ include "typescript-app.fullname" . }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}