# {{- if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "typescript-app.fullname" . }}
#   annotations:
#     kubernetes.io/ingress.class: {{ .Values.ingress.className }}
#     oci.oraclecloud.com/load-balancer-type: "lb"
#   spec:
#     rules:
#       {{- range .Values.ingress.hosts }}
#       - host: {{ .host }}
#         http:
#           paths:
#             {{- range .paths }}
#             - path: {{ .path }}
#               pathType: {{ .pathType }}
#               backend:
#                 service:
#                   name: {{ include "typescript-app.fullname" $ }}
#                   port:
#                     number: {{ $.Values.service.port }}
#               {{- end }}
#         {{- end }}
#   {{- end }}